<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="study" nsURI="http://study.org" nsPrefix="tdt4250.study">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programme" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="studyPlan" upperBound="-1"
        eType="#//StudyPlan" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="programmeCode" eType="#//programmeCode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StudyPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="spesialization" upperBound="-1"
        eType="#//Specialization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialization">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="totalPointsMustBeMoreThan30"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseSlot" upperBound="-1"
        eType="#//CourseSlot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallOrSpring" eType="#//FallOrSpring"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseSlot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mandatoryOrNotConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="mandatoryOrNotConstraint" value="if self.elective = true then not self.mandatoryCourse -> notEmpty() else true endif and if self.elective = false then not self.electiveCourses ->notEmpty() else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourse" eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="electiveCourses" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elective" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="programmeCode">
    <eLiterals name="Datateknologi5" literal="MTDT"/>
    <eLiterals name="Informatikk" value="1" literal="MSIT"/>
    <eLiterals name="Datateknologi2" value="2" literal="MIDT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxLength" value="8"/>
      <details key="minLength" value="6"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FallOrSpring">
    <eLiterals name="Fall"/>
    <eLiterals name="Spring" value="1"/>
  </eClassifiers>
</ecore:EPackage>
